name: Docker

on:
  workflow_dispatch: 
    inputs: 
      tag:
        description: "Tag"
        required: true
        

      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
              
    - name: Docker login
      run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
       
    - name: Docker builder
      run: |
          docker buildx use $(docker buildx create --platform linux/arm/v7)
         
    - name: Build & Push
      run: |
        docker buildx build --file Dockerfile --platform linux/arm/v7 --output "type=image,push=true" --tag orionpt/leantime:${{ github.event.inputs.tag }} .
      
    
